// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FoodApi.Data.Models
{
    [Table("Products", Schema = "dbo")]
    public partial class Products
    {
        public Products()
        {
            OrderDetails = new HashSet<OrderDetails>();
            ShoppingCartItems = new HashSet<ShoppingCartItems>();
        }

        [Key]
        public long Id { get; set; }
        [Required]
        [StringLength(250)]
        public string Name { get; set; }
        public string Detail { get; set; }
        [StringLength(50)]
        public string ImageUrl { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Price { get; set; }
        public bool IsPopularProduct { get; set; }
        public long CategoryId { get; set; }

        [ForeignKey("CategoryId")]
        [InverseProperty("Products")]
        public virtual Categories Category { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<ShoppingCartItems> ShoppingCartItems { get; set; }
    }
}